modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "seedsdelight"
version = "${version}"
displayName = "SeedsDelight"
authors = "HiedaCamellia"
description = '''

'''
#logoFile = ""

[[dependencies.seedsdelight]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seedsdelight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seedsdelight]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.seedsdelight]]
modId = "puzzleslib"
mandatory = true
versionRange = "[8.1.0,)"
ordering = "AFTER"
side = "BOTH"