modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "seedsdelight"
version = "${version}"
displayName = "SeedsDelight"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.seedsdelight]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seedsdelight]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seedsdelight]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.seedsdelight]]
modId = "puzzleslib"
type = "required"
versionRange = "[21.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "seedsdelight.mixins.json"
